### ISSUE TITLE
Switches between German and English language

### ISSUE THREAD

**Issue by rugk** [Gared/ep_message_all#10]
After I included https://github.com/Gared/ep_message_all/pull/9 now the languages in the panel are switching:

![langswitch](https://cloud.githubusercontent.com/assets/11966684/15297809/5f600a78-1b9c-11e6-9ab4-5c20d81af896.gif)

This means:
* If I'm on any other site than `message_to_all` it is in English
* If I'm on `message_to_all` it is in German

Without https://github.com/Gared/ep_message_all/pull/9  this issue did not happen.

**Comment by Gared** [comment]
This has nothing to do with your changes and happens also on the current version. The translation only gets loaded if you're on a page that requires the translation file.
So this is a feature request for etherpad core and not my plugin.
