### ISSUE TITLE
Send message to any user who opens previous pad

### ISSUE THREAD

**Issue by tamielbr** [Gared/ep_message_all#12]
Works great - wondering if it would be possible to have the message be sent to anyone that opens a previous pad (or connects to the pad). We have to remove our instance of etherpad and I need to notify everyone that has an old pad. Would this be easy/possible?

**Comment by Gared** [comment]
Great question! I created version 2.0.0 with support for your idea. Please update and test if this is what you want

**Comment by tamielbr** [comment]
Thanks, that's very kind. I am using a production version of Etherpad on a container so I'm investigating how to install it. I noticed you updated the repo to 2.0.0, so while I'm learning how to do this, I am also checking for when it will be picked up by https://static.etherpad.org/index.html, which would be easier to install the new version via /admin panel. I'll get back to you as soon as I test.

**Comment by Gared** [comment]
There is an argument in the docker container for plugins to install: ETHERPAD_PLUGINS 
https://etherpad.org/doc/latest/#index_examples

The plugin list is updated within a few hours usually. Now the new version of the plugin is shown in the plugin list

**Comment by tamielbr** [comment]
For some reason, I can't get it to update via /admin. I have tried updating multiple times and uninstalling/installing. It seems to be stuck on version 1.1.0. I will continue trying.

**Comment by tamielbr** [comment]
Restarted the service and it installed. Set the parameters (custom message, works) and time `"ep_message_all_show_message_time" : 86400,` in settings.json. But when I connect with other clients (using another mobile, private/incognito window) the message doesn't show. It only shows to open clients, as was with the previous version. My expectation, just to check:

1. I set the message and the timer, in my case 86400 = 24 hours (done);
2. I go to the admin panel and in Message to all and click "Send Message";
3. For the next 24 hours, anyone new client that opens a previously opened/edit pad, will see the message. 

Is this correct?

**Comment by Gared** [comment]
Your settings looking good. What version of etherpad do you use?

**Comment by tamielbr** [comment]
I'm on Version number: 1.8.5

**Comment by Gared** [comment]
Okay, found the problem. A hook in version 1.8.5 is working differently than in the newest version. I've updated the plugin to version 2.0.1

**Comment by tamielbr** [comment]
Perfect, it works! Thanks for your generosity on this. Very much appreciated.
