### ISSUE TITLE
Admin pane: Wrong link (does not rewrite)

### ISSUE THREAD

**Issue by rugk** [Gared/ep_message_all#6]
For Etherpad I use a config similar [to this](https://github.com/ether/etherpad-lite/wiki/How-to-put-Etherpad-Lite-behind-a-reverse-Proxy#from-subdirectory-url) (there also is a  rewrite for `/admin`).
However your link in your ACP is the only one nginx does not correctly rewrite, so you seem to use your link a bit differently than all other links in the admin panel.

E.g. the link should be `/pad/admin/message_to_all` whereas it actually is `/pad/message_to_all`.

The nginx rewrite is e.g. this: `rewrite /pad/admin/(.*) /admin/$1 break;`

Etherpad v1.6.0

**Comment by Gared** [comment]
I don't see any difference in creating my link. Maybe it's because of the underscores, but I'm not sure

**Comment by rugk** [comment]
I also think this is strange. BTW I'm running nginx/1.10.0.

So for all web admins having this issue you can add these lines to your nginx config as a workaround:
```
# rewrite for ep_message_all
# workaround for https://github.com/Gared/ep_message_all/issues/6
location /admin/message_to_all {
        rewrite /admin/message_to_all(.*) /MYSUBDIR/admin/message_to_all$1 redirect;
}
```

**Comment by rugk** [comment]
BTW you can have a look at https://github.com/eqr/ep_activepads and https://github.com/spcsser/ep_adminpads. They also have a link in the admin panel, but it is correct.

**Comment by rugk** [comment]
My PR solves my issue, but you might still have a look at [the plugins I suggested](https://github.com/spcsser/ep_adminpads/blob/afd49b119c0d743af453d75187ca64c9df4aa10f/index.js#L157) as they seem to have a more complex way to prefix the URL.

**Comment by rugk** [comment]
My issue is solved...
